# Generated by Django 3.0.2 on 2020-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertretungsplan_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VplanAktuell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=10, verbose_name='Tabellen Titel')),
                ('pos', models.IntegerField(verbose_name='Unterichtsstunde')),
                ('fach', models.CharField(max_length=100, verbose_name='Fach')),
                ('raum', models.CharField(max_length=100, verbose_name='Raum')),
                ('klasse', models.CharField(max_length=10, verbose_name='Klasse')),
                ('info', models.CharField(max_length=100, verbose_name='Informationen')),
                ('art', models.CharField(max_length=100, verbose_name='Art')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VplanAlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=10, verbose_name='Tabellen Titel')),
                ('pos', models.IntegerField(verbose_name='Unterichtsstunde')),
                ('fach', models.CharField(max_length=100, verbose_name='Fach')),
                ('raum', models.CharField(max_length=100, verbose_name='Raum')),
                ('klasse', models.CharField(max_length=10, verbose_name='Klasse')),
                ('info', models.CharField(max_length=100, verbose_name='Informationen')),
                ('art', models.CharField(max_length=100, verbose_name='Art')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Vplan_schueler',
        ),
    ]
