# Generated by Django 3.0.2 on 2020-03-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vertretungsplan_webapp', '0002_auto_20200330_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vplanDate', models.DateField(verbose_name='Vertretungsplan Datum')),
                ('vplanUploadDate', models.DateTimeField(auto_now_add=True, verbose_name='Vertretungsplan Uploaddatum')),
            ],
        ),
        migrations.CreateModel(
            name='VplanSchuelerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='Unterichtsstunde')),
                ('fach', models.CharField(max_length=100, verbose_name='Fach')),
                ('raum', models.CharField(max_length=100, verbose_name='Raum')),
                ('klasse', models.CharField(max_length=10, verbose_name='Klasse')),
                ('info', models.CharField(max_length=100, verbose_name='Informationen')),
                ('art', models.CharField(max_length=100, verbose_name='Art')),
                ('vplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertretungsplan_webapp.Vplan')),
            ],
        ),
    ]
