# Generated by Django 3.0.2 on 2020-03-31 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertretungsplan_webapp', '0003_vplan_vplanschuelerentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VplanAktuell',
        ),
        migrations.DeleteModel(
            name='VplanAlt',
        ),
    ]
