# Generated by Django 3.0.2 on 2020-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kurs',
            field=models.CharField(max_length=10, verbose_name='Kurs'),
        ),
    ]
