# Generated by Django 3.0.2 on 2020-04-03 23:20

from django.db import migrations, models
import userManagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20200330_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='klasse',
            field=models.CharField(blank=True, help_text='Muss die Klasse sein nicht der Kurs!.', max_length=3, validators=[userManagement.validators.UnicodeClassValidator()], verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kurs',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kurs'),
        ),
    ]
