# Generated by Django 3.0.2 on 2020-04-03 23:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0003_auto_20200404_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SchuelerProfile',
        ),
        migrations.RenameField(
            model_name='schuelerprofile',
            old_name='kurs',
            new_name='kurse',
        ),
    ]
