# Generated by Django 3.0.2 on 2020-04-04 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0004_auto_20200404_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schuelerprofile',
            name='kurse',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kurs'),
        ),
        migrations.CreateModel(
            name='LehrerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(blank=True, help_text='Ihr Kürzel als Lehrer.', max_length=4, verbose_name='Lehrer Kürzel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
