# Generated by Django 3.0.2 on 2020-04-07 22:54

from django.db import migrations, models
import userManagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_auto_20200405_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schuelerprofile',
            name='klasse',
            field=models.CharField(blank=True, help_text='Muss die Klasse sein nicht der Kurs!', max_length=3, validators=[userManagement.validators.class_validator], verbose_name='Klasse'),
        ),
        migrations.AlterField(
            model_name='schuelerprofile',
            name='kurse',
            field=models.CharField(blank=True, max_length=150, validators=[userManagement.validators.kurs_validator], verbose_name='Kurse'),
        ),
    ]
